name: pacman_juego
description: "un capricho de jova."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.38.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/jova_logo.png
    - assets/images/game_over.png
    - assets/images/win.png
    - assets/images/vance.png
    - assets/images/shardox.png
    - assets/images/shardoxniga.png
    - assets/images/vespakron.png
    - assets/images/vespakronniga.png
    - assets/images/kyros.png
    - assets/images/kyrosniga.png
    - assets/images/pyros.png
    - assets/images/pyrosniga.png
    - assets/images/mori.png
    - assets/images/rimora.png
    - assets/images/mydra.png